server:
  host: localhost:8080
  contextPath: /aac

jdbc:
  dialect: org.hibernate.dialect.MySQLDialect
  driver: com.mysql.jdbc.Driver

spring:
  messages:
    basename: resources/internal
    encoding: UTF-8


security:
  restricted: false
  basic:
      enabled: false


logging:
  level:
    org.springframework.security: INFO

swagger:
  title: 
    AAC: AAC API - Profile and token info 
    AACApiKey: AAC API - API Access Key management
    AACAuthorization: AAC API - Authorization management 
    AACRoles: AAC API - Role management 
  description: 
    AAC: Authorization and Authentication Control APIs - Profile and token info 
    AACApiKey: Authorization and Authentication Control APIs - API Key validation and management
    AACAuthorization: Authorization and Authentication Control APIs - Authorization management 
    AACRoles: Authorization and Authentication Control APIs - Role managment
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
  contact:
    name:  Smart Community Lab
    url: www.smartcommunitylab.it
    email: info@smartcommunitylab.it