server:
  host: localhost:8080
  contextPath: /aac

jdbc:
  dialect: org.hibernate.dialect.MySQLDialect
  driver: com.mysql.jdbc.Driver

spring:
  messages:
    basename: resources/internal
    encoding: UTF-8


security:
  restricted: false
  basic:
      enabled: false


logging:
  level:
    org.springframework.security: INFO
